### ISSUE TITLE
firmware key

### ISSUE THREAD

**Issue by carson512** [ludwig-v/psa-nac-firmware-reverse-engineering#3]
I saw the update 21.07.88-42-r0.key file.
But the firmware verison maybe the 22-07-88-42. the file full name is PSA_ovip-int-firmware-nac-dpca_22-07-88-42_NAC-r0_NAC_CN_WAVE2.

> [root@Centos psa]# bash ./Scripts/decrypt_SWL.sh SWL/ ./Firmware_Keys/NAC_CN_WAvE2/21.07.88-42-r0.key
SWL/001315201563355623/Certificates/DPCA-OVIP-CS-G1.crl seems already decrypted !
SWL/001315201563355623/Certificates/DPCA-OVIP-CS-G1.crt seems already decrypted !
SWL/001315201563355623/Certificates/PSA-OVIP-G1.crl seems already decrypted !
SWL/001315201563355623/Firmware/AUTO/1010101/NAC_B2/OVIP/1010101.FRG has not been decrypted, the key is probably invalid !
Stopping
SWL/001315201563355623/Firmware/AUTO/1010103/NAC_B2/OVIP/rootfs.fsn parts have been merged !
SWL/001315201563355623/Firmware/AUTO/1010122/NAC_B2/OVIP/ui1-app-data-resource.tar.gz parts have been merged !

ps: I want to check where the Navi app mainprogram contain? The fileware or the Navi app updatepack.
THX

**Comment by ludwig-v** [comment]
./Firmware_Keys/NAC_CN_WA **v** E2 ?!

Respect the case and make sure openssl is installed on the system.

The key works fine:

> ./SWL/001315201563355623/Certificates/DPCA-OVIP-CS-G1.crl seems already decrypted !
./SWL/001315201563355623/Certificates/DPCA-OVIP-CS-G1.crt seems already decrypted !
./SWL/001315201563355623/Certificates/PSA-OVIP-G1.crl seems already decrypted !
./SWL/001315201563355623/Firmware/AUTO/1010101/NAC_B2/OVIP/1010101.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010102/NAC_B2/OVIP/1010102.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010103/NAC_B2/OVIP/rootfs.fsn has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010103/NAC_B2/OVIP/rootfs.fsn01 has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010103/NAC_B2/OVIP/rootfs.fsn02 has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010104/HIFI/OVIP/1010104.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010104/no_HIFI/OVIP/1010104_noHifi.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/101010a/NAC_B2/OVIP/101010a.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/101010b/NAC_B2/OVIP/tsw.fsn has been decrypted
./SWL/001315201563355623/Firmware/AUTO/101010c/NAC/CN_BL_01/101010c_CN_BL_01.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/101010c/NAC/CN_BL_02/101010c_CN_BL_02.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/101010d/NAC/CN_BL_01/101010d_CN_BL_01.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/101010d/NAC/CN_BL_02/101010d_CN_BL_02.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010110/NAC_B2/OVIP/1010110.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010121/NAC_B2/OVIP/radio-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010122/NAC_B2/OVIP/ui1-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010122/NAC_B2/OVIP/ui1-app-data-resource.tar.gz01 has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010122/NAC_B2/OVIP/ui1-app-data-resource.tar.gz02 has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010123/NAC_B2/OVIP/nav-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010124/NAC_B2/OVIP/ui2-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010181/NAC_B2/OVIP/speech1-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010182/NAC_B2/OVIP/speech2-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010183/NAC_B2/OVIP/speech3-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010184/NAC_B2/OVIP/speech4-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010185/NAC_B2/OVIP/speech5-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010186/NAC_B2/OVIP/datastore_rw-app-data-resource.tar.gz has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010640/GPS/OVIP/1010640_GPS.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/1010640/noGPS/OVIP/1010640_noGPS.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/4010212/NAC_B2/OVIP/4010212.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/4010214/NAC_B2/OVIP/4010214.FRG has been decrypted
./SWL/001315201563355623/Firmware/AUTO/packages/installList.inst seems already decrypted !
./SWL/001315201563355623/Firmware/AUTO/packages/oip-ssw-security-usergroup-helper-swl_1.0.14-r0_armv7a.ipk has been decrypted
./SWL/001315201563355623/Firmware/AUTO/packages/ovip-install-universe-after-swl_1.0-r0_armv7a.ipk has been decrypted
./SWL/001315201563355623/Firmware/AUTO/packages/ovip-int-core-emb-registry-ids-swl_22.07.88.42_NAC-r0_armv7a.ipk has been decrypted
./SWL/001315201563355623/Firmware/AUTO/packages/ovip-int-firmware-nac-dpca_22.07.88.42_NAC-r0_armv7a.ipk has been decrypted
./SWL/001315201563355623/Firmware/AUTO/packages/ovip-int-firmware-version_22.07.88.42_NAC-r0_armv7a.ipk has been decrypted
./SWL/001315201563355623/Firmware/AUTO/packages/Packages.gz seems already decrypted !
./SWL/001315201563355623/Firmware/FirmwareList.ini seems already decrypted !
./SWL/001315201563355623/HashList.ini seems already decrypted !
./SWL/001315201563355623/MediaHeader/MediaVersion.ini seems already decrypted !
./SWL/001315201563355623/Firmware/AUTO/1010103/NAC_B2/OVIP/rootfs.fsn parts have been merged !
./SWL/001315201563355623/Firmware/AUTO/1010122/NAC_B2/OVIP/ui1-app-data-resource.tar.gz parts have been merged !

**Comment by carson512** [comment]
I try to modify the rootfs.fsn.
Then I just decrypt rootfs.fsn02.And use the crt file to encrypt the rootfs.fsn02.

> openssl smime -encrypt -binary -in /home/ubuntu/psa-nac-firmware-reverse-engineering-main/rootfsdir/decrypted/NAC_B2/OVIP/rootfs.fsn02 -out /home/ubuntu/psa-nac-firmware-reverse-engineering-main/rootfsdir/test02.fsn /home/ubuntu/psa-nac-firmware-reverse-engineering-main/SWL/001315201563355623/Certificates/DPCA-OVIP-CS-G1.crt

But the file out is not same with the org. Is that the public key or encrypt command error.I think just the key error.
How to find the original public key.

PS:Is that possible update the firmware with the modify rootfs.fsn.
